kiegroup/rhpam-kogito-operator

Jenkinsfile

Jira issue : https://issues.redhat.com/browse/KOGITO-4603

[KOGITO-4603] - Setup Jenkins pipeline for BDD test

---

Jenkinsfile
Makefile
api/v1/zz_generated.openapi.go
go.mod
go.sum
hack/run-tests.sh
hack/run-tests.sh.bats
hack/update-bundle.sh
test/.default_config
test/framework/kogitobuild.go
test/framework/kogitoruntime.go
test/installers/rhpam_kogito_installer.go
test/main_test.go
test/steps/data.go
test/steps/kogitobuild.go
test/steps/kogitoruntime.go
test/steps/mappers/create_kogito_build.go
test/steps/openshift.go
test/steps/operator.go

https://issues.redhat.com/browse/KOGITO-4605

[KOGITO-4605] Setup BDD test for Product kogito operator

---

main.go

See: https://issues.redhat.com/browse/KOGITO-4797
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

[KOGITO-4797] - Disable Dev mode in logging by default

---

.github/bot-files/reviewers.yml

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

Updating bot reviewers.yml

---

controllers/runtime_deployer.go
go.mod
go.sum
meta/meta.go

See: https://issues.redhat.com/browse/KOGITO-4888
Upstream PR: https://github.com/kiegroup/kogito-operator/pull/836
Many thanks for submiting your Pull Request :heart:! 
Please make sure that your PR meets the following requirements:

[KOGITO-4888] Update Prometheus operator GitHub link

---

README.md
image-prod.yaml
image.yaml
modules/org.kie.kogito.builder/install.sh

See other PR: https://github.com/kiegroup/rhpam-kogito-operator/pull/20

KOGITO-4851 Prod changes to build in OSBS

---

test/.default_config

[1.5.x] Use 1.5 images and examples for tests

---

controllers/kogitobuild_controller.go
controllers/kogitoruntime_controller.go
controllers/runtime_deployer.go
go.mod
go.sum
internal/kogitobuild.go
internal/kogitoruntime.go

https://issues.redhat.com/browse/KOGITO-5005

[KOGITO-5005] - Operator print irrelevant metadata in logs

---

controllers/kogitoruntime_controller.go
go.mod
go.sum

https://issues.redhat.com/browse/KOGITO-4898

[KOGITO-4898] Set probe defaults based on YAML action values

---

go.mod
go.sum
test/pkg/framework/kogitobuild.go
test/pkg/steps/deploy_files.go
test/pkg/steps/kogitobuild.go

https://issues.redhat.com/browse/KOGITO-5063

[KOGITO-5063] BDD tests: Support using builder images from insecure registry

---

image-bundle.yaml
image-prod.yaml
image.yaml
modules/org.kie.kogito.builder/module.yaml
modules/org.kie.kogito.bundleinstall/module.yaml
modules/org.kie.kogito.gomoddownloader/module.yaml

See https://github.com/kiegroup/rhpam-kogito-operator/pull/30

[1.5.x][BXMSPROD-1306] Update to  include micro in the version.

---

Jenkinsfile
Makefile
bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
go.sum
hack/bump-version.sh.bats
hack/update-bundle.sh
image-bundle.yaml
rhpam-kogito-operator.yaml
test/installers/rhpam_kogito_installer.go

Below cmd needs to be executed to create prod operator bundle:
`make bundle-prod-build IMG=registry.redhat.io/rh-osbs/rhpam-7-rhpam-kogito-operator:7.11.0 BUILDER=osbs`

[KOGITO-5175] - [1.5.x] - Changes for productized build of Operator bundle

---

.jenkins/dsl/jobs.groovy
Jenkinsfile.upstream-operator-sync

https://issues.redhat.com/browse/KOGITO-5272
Following https://github.com/kiegroup/rhpam-kogito-operator/pull/42, updating the sync job with new image full tag

[KOGITO-5272] Update operator image name in sync job

---

Makefile
bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml

Jira Issue : https://projects.engineering.redhat.com/browse/SPMM-6427

Upgrade bundle version to rhpam-kogito-operator.v7.11.0-1

---

RELEASE_NOTES.md
controllers/kogitobuild_controller.go
controllers/runtime_deployer.go
go.mod
go.sum
internal/kogitobuild.go
internal/labels.go

See: https://issues.redhat.com/browse/RHPAM-3681
Cherry-pick of #48.
Please make sure that your PR meets the following requirements:

[1.5.x] [RHPAM-3681] Add metering labels for Kogito pods

---

.jenkins/dsl/Jenkinsfile.seed

https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/rhpam-kogito-operator/pull/53

[1.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#53)

---

Jenkinsfile.upstream-operator-sync

https://issues.redhat.com/browse/KOGITO-5326
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/212
- https://github.com/kiegroup/kogito-runtimes/pull/1449
- https://github.com/kiegroup/optaplanner/pull/1436
- https://github.com/kiegroup/kogito-apps/pull/945
- https://github.com/kiegroup/kogito-examples/pull/800
- https://github.com/kiegroup/kogito-images/pull/602
- https://github.com/kiegroup/kogito-operator/pull/944
- https://github.com/kiegroup/rhpam-kogito-operator/pull/56

[KOGITO-5326] Setup deploy/promote notifications on demand

---

hack/ci/operator-ensure-manifests.sh
hack/ci/run-olm-tests.sh
hack/env.sh

Correct olm tests

---

go.tools.mod
go.tools.sum
hack/addheaders.sh

Fix build problem with addlicense library

---

Makefile
api/v1/kogitoinfra_types.go
bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/kogitoinfra_controller.go
go.mod
go.sum
hack/tests-clean-files.sh
hack/tests-download-files.sh
rhpam-kogito-operator.yaml
test/pkg/framework/kogitoinfra.go
test/pkg/steps/data.go
test/pkg/steps/kogitoinfra.go

https://issues.redhat.com/browse/KOGITO-5685
Depends on https://github.com/kiegroup/kogito-operator/pull/968

KOGITO-5685 RHPAM BDD tests with events

---

Jenkinsfile.upstream-operator-sync

Related PRs:
- https://github.com/kiegroup/kogito-operator/pull/985
- https://github.com/kiegroup/rhpam-kogito-operator/pull/66

BDD: Removed usage of Maven mirror

---

Makefile
go.mod
go.sum
hack/update-dependencies.sh
test/pkg/installers/amqstreams_installer.go

+ corrections
https://issues.redhat.com/browse/KOGITO-5742

KOGITO-5742 BDD: Setup amq streams to 1.8.x

---

go.mod
go.sum
hack/env.sh
hack/tests-prepare.sh

* KOGITO-5762 BDD: Cleanup crds
* modified scripts

[1.11.x] Update kogito-operator reference

---

go.mod
go.sum
hack/env.sh
hack/tests-prepare.sh
test/.default_config
test/pkg/framework/kogitobuild.go

Update kogito-operator reference

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.upstream-operator-sync
go.mod
go.sum
hack/env.sh
hack/tests-clean.sh
hack/tests-prepare.sh
test/pkg/framework/kogitobuild.go
test/pkg/steps/deploy_files.go
test/pkg/steps/kogitobuild.go

https://issues.redhat.com/browse/KOGITO-5865

[1.11.x] [KOGITO-5865] BDD: Cleanup installed operators

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.upstream-operator-sync
go.mod
go.sum
hack/env.sh
hack/tests-clean.sh
hack/tests-prepare.sh
hack/update-dependencies.sh
test/.default_config
test/pkg/framework/kogitobuild.go

https://issues.redhat.com/browse/KOGITO-5865
https://issues.redhat.com/browse/KOGITO-5888

[KOGITO-5865][KOGITO-5888] BDD: Cleanup installed operators and remove namespace option

---

.ci/jenkins/dsl/jobs.groovy

cherry-pick: https://github.com/kiegroup/rhpam-kogito-operator/pull/68
https://issues.redhat.com/browse/KOGITO-5730
This will reorganize the different jobs in a specific branch folder and allow automatically deleting jobs when the concerned branch is removed from the [main config](https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/seed/config/main.yaml#L2)
Example: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-5730/
Here are the new mappings: 
- nightly/{branch}/... => {branch}/nightly/...
- release/{branch}/... => {branch}/release/...
- pullrequest/{branch}/... => {branch}/pullrequest/...
- tools/{branch}/... => {branch}/tools/...
- other/{branch}/... => {branch}/other/...
**All PRs should be merged at the same time …

[1.11.x] KOGITO-5730 Update DSL folder structure (#68)

---

.ci/jenkins/Jenkinsfile
.ci/jenkins/Jenkinsfile.upstream-operator-sync
Makefile
go.mod
go.sum
go.tools.mod
go.tools.sum
hack/ci/install-operator-sdk.sh
hack/ci/uninstall-operator-sdk.sh

[1.11.x] BXMSPROD-1478 Setup Jenkins pipelines with new golang

---

modules/org.kie.kogito.builder/install.sh

See: https://issues.redhat.com/browse/KOGITO-6230

[KOGITO-6230] remove OS and arch to have multiarch build

---

image-bundle.yaml
image-prod.yaml
image.yaml

Add additional architectures for multi-arch operator + bundle
